### ISSUE TITLE
Crash when calling TodoReview while it's tab is already open

### ISSUE THREAD

**Issue by Code-Curious** [jonathandelgado/SublimeTodoReview#131]
Hi,

Whenever I run one of the TodoReview commands and the TodoReview tab is already open (I ran the command before), instead of switching to that tab or refreshing it, Sublime text  (and my whole computer) freezes for a minute until plugin_host crashes.

I am using ST3 on Windows by the way

**Comment by diego1araujo** [comment]
+1 yep. can confirm

**Comment by jonathandelgado** [comment]
Is there a new sublime build causing this? Never had this issue before.

Away from an environment where I can test this. Any console output? OS? Sublime version?

**Comment by diego1araujo** [comment]
Just to clarify.. I see a similar issue but my pc does not freeze. (Windows 7 ST3 Build 3083).

The problem I've noticed is when TodoReview tab is already open and I run the command to execute again, It doesn't switch to TodoReview tab and I see a blank page as well.

![todoreview](https://cloud.githubusercontent.com/assets/4531801/10120209/fa8dfa28-6486-11e5-9eaa-e3d365cd0f66.gif)

**Comment by jonathandelgado** [comment]
Has this functionality ever worked for your @diego1araujo?

**Comment by Code-Curious** [comment]
I am using ST build 3083 on Windows 8

**Comment by marekkaczkowski** [comment]
+1 same here ;(

**Comment by jonathandelgado** [comment]
Fixed by #133 and 5105f7133883f3522c1b417fd231d49adae0de06

Thanks for the report.

**Comment by Code-Curious** [comment]
You are welcome, unfortunatly, I am sorry to say that  v3.0.7 has not fixed this issue, I still get the huge  freeze when running TodoReview while its tab is still open.

**Comment by FichteFoll** [comment]
Still experiencing similar issue:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\TodoReview\TodoReview.py", line 233, in run
    self.draw_header()
  File "C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\TodoReview\TodoReview.py", line 292, in draw_header
    date = datetime.datetime.now().strftime(datestr)
TypeError: strftime() argument 1 must be str, not None
```

Only occurs when the TodoReviw view is open already. Trying again works.

**Comment by jonathandelgado** [comment]
@FichteFoll Just fixed that in 636914b for you, seems like it was the same issue as #133, i'm not sure why the sublime settings objects stop working out of the blue.

**Comment by FichteFoll** [comment]
Thanks. I looked into the code briefly but couldn't spot an obvious flaw during that time.

The fact that it is so reliably reproducable and I haven't had any problems with settings objects recently whatsoever leads to the thought it might be an error in TodoReview's code, however.
